
# data path
[PATHS]
egg_price_data_path = D:\egg_price_procject\output\egg_price_data.csv
festivals_data_path = D:\egg_price_procject\output\india_festival_dates.csv
weather_data_path = D:\egg_price_procject\output\india_weather_data.csv


[CITY]
#city which are goint in model training and analysis   

    ;     ['Ahmedabad', 'Ajmer', 'Barwala', 'Bengaluru', 'Brahmapur',
    ;    'Chennai', 'Delhi', 'E.Godavari', 'Hospet', 'Jabalpur', 'Kolkata',
    ;    'Ludhiana', 'Mumbai', 'Mysuru', 'Namakkal', 'Pune', 'Raipur',
    ;    'Surat', 'Vijayawada', 'Vizag', 'W.Godavari', 'Warangal',
    ;    'Allahabad', 'Bhopal', 'Indore', 'Kanpur', 'Luknow', 'Muzaffurpur',
    ;    'Nagpur', 'Patna', 'Ranchi', 'Varanasi', 'Chittoor', 'Hyderabad']


city = Barwala, Hyderabad, Delhi, Indore, Varanasi, Ajmer

[STORE]
path = D:\egg_price_procject\output\main_data